image: node:14-alpine

# Cache modules in between jobs per-branch
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - server/node_modules/

stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags:
    - docker
  script:
    - cd server
    - npm install

test:
  stage: test
  tags:
    - docker
  services:
    - name: mvertes/alpine-mongo:latest
      alias: mongo
  variables:
    MONGODB_URI: "mongodb://mongo:27017/serverTestDB"
  script:
    - cd server
    - npm run ci-test

deploy:
  stage: deploy
  tags:
    - docker
  image: ruby:alpine
  script:
    - apk update && apk add git curl
    - gem install dpl
    - dpl --provider=heroku --app=sembook --api-key=d20634b1-5b03-4c33-ae72-98cc4c100ea8
  environment:
    name: production
    url: https://sembook.herokuapp.com/
  only:
    refs:
      - master
    variables:
      - $HEROKU_APP_NAME
      - $HEROKU_API_KEY
